describe('test visualizar Horario', () => {
    it('cenario1', () => {  //Rafaela Lima de Albuquerque com o CPF 70250518231 e a matrícula raf12345, estuda no colégio Dom Domingos II e está cadastrada no sistema da SmartSchool , e está cadastrada na 1º série na turma A do fundamental I, onde nas segundas-feiras incluem as matérias de: Matemática das 8h às 9h, Português das 9h às 10h, Português das 10:30 às 11:30 e Matemática de 11:30 às 12:30. Nas terças-feiras incluem as matérias de: História das 8h às 9h, Geografia das 9h às 10h, Geografia das 10:30 às 11:30 e História de 11:30 às 12:30. Nas quartas-feiras incluem as matérias de: Português das 8h às 9h, Matemática das 9h às 10h, Matemática das 10:30 às 11:30 e Português de 11:30 às 12:30. Nas quintas-feiras incluem as matérias de Geografia das 8h às 9h, História das 9h às 10h, História das 10:30 às 11:30 e Geografia de 11:30 às 12:30. Nas sextas-feiras incluem as matérias de Matemática 8h às 9h, Português das 9h às 10h, História das 10:30 às 11:30 e Geografia de 11:30 às 12:30. Então será retornado em sua grade horária essas matérias e seus respectivos horários com base na 3º série na turma A, e não de Ricardo Couto, que está na 3º série na turma B;

        cy.visit('/admin'); //pagina http://127.0.0.1:8000/
        cy.get('#id_username').type('ygoradmin')
        cy.get('#id_password').type('ygor8500')
        cy.get('.submit-row > input').click()
        cy.get('.model-user > :nth-child(2) > .addlink').click()
        cy.get('#id_username').type('45698732109')
        cy.get('#id_password1').type('mar12345')
        cy.get('#id_password2').type('mar12345')
        cy.get('.default').click()

        cy.get('.model-useraluno > td > .addlink')
        cy.get('.model-useraluno > td > .addlink').click()
        cy.get('#id_user').select('45698732109');
        cy.get('#id_matricula').type('mar12345')
        cy.get('#id_nome').type('Maria Alice Rosa')
        cy.get('#id_cpf').type('45698732109')
        cy.get('#id_data_de_nascimento').type('18/03/2017')
        cy.get('#id_endereco').type('Rua José Paraíso 88/701')
        cy.get('#id_colegio').type('Maria Cecilia')
        cy.get('#id_serie').type('2')
        cy.get('#id_turma').type('A')
        cy.get('#id_email').type('mariacr@gmail.com')
        cy.get('#id_nome_responsavel').type('Marcelo Rosa')
        cy.get('#id_cpf_responsavel').type('70345612603')
        cy.get('#id_telefone').type('81985060793')
        cy.get('#id_email_responsavel').type('marcelros@gmail.com')
        cy.get('.default').click()
        
        cy.get('.model-horarioaula > td > .addlink').click()
        cy.get('#id_colegio').type('Maria Cecilia')
        cy.get('#id_serie').type('2')
        cy.get('#id_turma').type('A')
        cy.get('#id_horario_inicio_1').type('08:00')
        cy.get('#id_horario_fim_1').type('09:00')
        cy.get('#id_horario_inicio_2').type('09:00')
        cy.get('#id_horario_fim_2').type('10:00')
        cy.get('#id_horario_inicio_3').type('10:30')
        cy.get('#id_horario_fim_3').type('11:30')
        cy.get('#id_horario_inicio_4').type('11:30')
        cy.get('#id_horario_fim_4').type('12:30')
        cy.get('#id_seg_materia_do_horario_1').type('Portugûes')
        cy.get('#id_seg_materia_do_horario_2').type('Matemática')
        cy.get('#id_seg_materia_do_horario_3').type('Português')
        cy.get('#id_seg_materia_do_horario_4').type('Matemática')
        cy.get('#id_ter_materia_do_horario_1').type('Geografia')
        cy.get('#id_ter_materia_do_horario_2').type('Geografia')
        cy.get('#id_ter_materia_do_horario_3').type('Português')
        cy.get('#id_ter_materia_do_horario_4').type('História')
        cy.get('#id_quar_materia_do_horario_1').type('Português')
        cy.get('#id_quar_materia_do_horario_2').type('Matemática')
        cy.get('#id_quar_materia_do_horario_3').type('Matemática')
        cy.get('#id_quar_materia_do_horario_4').type('História')
        cy.get('#id_quin_materia_do_horario_1').type('Português')
        cy.get('#id_quin_materia_do_horario_2').type('História')
        cy.get('#id_quin_materia_do_horario_3').type('Geografia')
        cy.get('#id_quin_materia_do_horario_4').type('Português')
        cy.get('#id_sex_materia_do_horario_1').type('Geografia')
        cy.get('#id_sex_materia_do_horario_2').type('Matemática')
        cy.get('#id_sex_materia_do_horario_3').type('Geografia')
        cy.get('#id_sex_materia_do_horario_4').type('História')

        cy.get('.default').click()

        cy.visit('/');
        cy.get('[href="/aluno/"] > .botao').click()
        cy.get('#username').type('45698732109')
        cy.get('#password').type('mar12345')
        cy.get('.btn-submit').click()

        cy.get(':nth-child(3) > .nav-menu-texto').click()

   })

   it('cenario2', () => {
    cy.visit('/admin'); //pagina http://127.0.0.1:8000/
    cy.get('#id_username').type('ygoradmin')
    cy.get('#id_password').type('ygor8500')
    cy.get('.submit-row > input').click()
    cy.get('.model-user > :nth-child(2) > .addlink').click()
    cy.get('#id_username').type('70250518231')
    cy.get('#id_password1').type('raf12345')
    cy.get('#id_password2').type('raf12345')
    cy.get('.default').click()
    cy.get('.model-useraluno > td > .addlink').click()
    cy.get('#id_user').select('70250518231');
    cy.get('#id_matricula').type('raf12345')
    cy.get('#id_nome').type('Rafela Lima de Alburquerque')
    cy.get('#id_cpf').type('70250518231')
    cy.get('#id_data_de_nascimento').type('01/05/2018')
    cy.get('#id_endereco').type('Armazém Original - Mercado da Torre - R. José Bonifácio, 747 - Torre, Recife - PE, 50710-001')
    cy.get('#id_colegio').type('Dom Domingos II')
    cy.get('#id_serie').type('1')
    cy.get('#id_turma').type('A')
    cy.get('#id_email').type('rafalima@gmail.com')
    cy.get('#id_nome_responsavel').type('Maria Antonieta Solene Lima')
    cy.get('#id_cpf_responsavel').type('73681609210')
    cy.get('#id_telefone').type('81997725630')
    cy.get('#id_email_responsavel').type('mantonieta@gmail.com')
    cy.get('.default').click()
    cy.get('.model-horarioaula > td > .addlink').click()
    cy.get('#id_colegio').type('Dom Domingos II')
    cy.get('#id_serie').type('1')
    cy.get('#id_turma').type('A')
    cy.get('#id_horario_inicio_1').type('08:00')
    cy.get('#id_horario_fim_1').type('09:00')
    cy.get('#id_horario_inicio_2').type('09:00')
    cy.get('#id_horario_fim_2').type('10:00')
    cy.get('#id_horario_inicio_3').type('10:30')
    cy.get('#id_horario_fim_3').type('11:30')
    cy.get('#id_horario_inicio_4').type('11:30')
    cy.get('#id_horario_fim_4').type('12:30')
    cy.get('#id_seg_materia_do_horario_1').type('Matemática')
    cy.get('#id_seg_materia_do_horario_2').type('Português')
    cy.get('#id_seg_materia_do_horario_3').type('Português')
    cy.get('#id_seg_materia_do_horario_4').type('Matemática')
    cy.get('#id_ter_materia_do_horario_1').type('História')
    cy.get('#id_ter_materia_do_horario_2').type('Geografia')
    cy.get('#id_ter_materia_do_horario_3').type('Geografia')
    cy.get('#id_ter_materia_do_horario_4').type('História')
    cy.get('#id_quar_materia_do_horario_1').type('Português')
    cy.get('#id_quar_materia_do_horario_2').type('Matemática')
    cy.get('#id_quar_materia_do_horario_3').type('Matemática')
    cy.get('#id_quar_materia_do_horario_4').type('Português')
    cy.get('#id_quin_materia_do_horario_1').type('Geografia')
    cy.get('#id_quin_materia_do_horario_2').type('História')
    cy.get('#id_quin_materia_do_horario_3').type('História')
    cy.get('#id_quin_materia_do_horario_4').type('Geografia')
    cy.get('#id_sex_materia_do_horario_1').type('Matemática')
    cy.get('#id_sex_materia_do_horario_2').type('Português')
    cy.get('#id_sex_materia_do_horario_3').type('História')
    cy.get('#id_sex_materia_do_horario_4').type('Geografia')
    cy.get('.default').click()
    cy.get('#logout-form > button').click()
    cy.visit('/')
    cy.get('[href="/aluno/"] > .botao').click()
    cy.get('#username').type('70250518231')
    cy.get('#password').type('raf12345')
    cy.get('.btn-submit').click()
    cy.get(':nth-child(3) > .nav-menu-texto').click()
    })
})

