describe('test registrar notas', () => {
    it ('cenario', () => {
        cy.exec('py manage.py flush --noinput', { failOnNonZeroExit: false });
        cy.exec('py manage.py create_superuser', { failOnNonZeroExit: false });

        cy.visit('/admin'); // http://127.0.0.1:8000/
        cy.get('#id_username').type('admin')
        cy.get('#id_password').type('123456')
        cy.get('.submit-row > input').click()
        cy.wait(1000)

        cy.get('.model-disciplina > :nth-child(2) > .addlink').click()
        cy.get('#id_codigo').type('1')
        cy.get('#id_nome').type('Matemática')
        cy.get('#id_carga_horaria').type('40')
        cy.get('#id_ementa').type('Teste')
        cy.get('.default').click()

        cy.get('.model-disciplina > :nth-child(2) > .addlink').click()
        cy.get('#id_codigo').type('2')
        cy.get('#id_nome').type('Português')
        cy.get('#id_carga_horaria').type('40')
        cy.get('#id_ementa').type('Teste')
        cy.get('.default').click()

        cy.get('.model-disciplina > :nth-child(2) > .addlink').click()
        cy.get('#id_codigo').type('3')
        cy.get('#id_nome').type('Inglês')
        cy.get('#id_carga_horaria').type('40')
        cy.get('#id_ementa').type('Teste')
        cy.get('.default').click()

        cy.get('.model-disciplina > :nth-child(2) > .addlink').click()
        cy.get('#id_codigo').type('4')
        cy.get('#id_nome').type('História')
        cy.get('#id_carga_horaria').type('40')
        cy.get('#id_ementa').type('Teste')
        cy.get('.default').click()

        cy.get('.model-turma > td > .addlink').click()
        cy.get('#id_serie').type('1')
        cy.get('#id_turma').type('A')
        cy.get('#id_materia_1').type('Matemática')
        cy.get('#id_codigo_materia_1').type('1')
        cy.get('#id_materia_2').type('Português')
        cy.get('#id_codigo_materia_2').type('2')
        cy.get('#id_materia_3').type('Inglês')
        cy.get('#id_codigo_materia_3').type('3')
        cy.get('#id_materia_4').type('História')
        cy.get('#id_codigo_materia_4').type('4')
        cy.get('.default').click()

        cy.get('.model-user > :nth-child(2) > .addlink').click()
        cy.get('#id_username').type('34489066420')
        cy.get('#id_password1').type('ygor1234')
        cy.get('#id_password2').type('ygor1234')
        cy.get('.default').click()
        cy.get('.model-userprofessor > td > .addlink').click()
        cy.get('#id_user').select('34489066420');
        cy.get('#id_nome').type('Ygor Bernardes')
        cy.get('#id_matricula').type('ygor1234')
        cy.get('#id_cpf').type('34489066420')
        cy.get('#id_data_de_nascimento').type('11/01/1974')
        cy.get('#id_telefone').type('81982355859')
        cy.get('#id_email').type('ygor@gmail.com')
        cy.get('.default').click()
        cy.wait(3000)

        cy.get('.model-user > :nth-child(2) > .addlink').click()
        cy.get('#id_username').type('70250518231')
        cy.get('#id_password1').type('ygor8500')
        cy.get('#id_password2').type('ygor8500')
        cy.get('.default').click()
        cy.wait(3000)
        cy.get('.model-useraluno > td > .addlink').click()
        cy.get('#id_user').select('70250518231');
        cy.get('#id_matricula').type('raf12345')
        cy.get('#id_nome').type('Rafela Lima de Alburquerque')
        cy.get('#id_cpf').type('70250518231')
        cy.get('#id_data_de_nascimento').type('01/05/2018')
        cy.get('#id_endereco').type('Armazém Original - Mercado da Torre - R. José Bonifácio, 747 - Torre, Recife - PE, 50710-001')
        cy.get('#id_colegio').type('Dom Domingos II')
        cy.get('#id_serie').type('1')
        cy.get('#id_turma').type('A')
        cy.get('#id_nome_responsavel').type('Maria Antonieta Solene Lima')
        cy.get('#id_cpf_responsavel').type('73681609210')
        cy.get('#id_telefone').type('81997725630')
        cy.get('#id_email_responsavel').type('mantonieta@gmail.com')
        cy.get('#id_peso').clear()
        cy.get('#id_peso').type('25.5')
        cy.get('#id_altura').clear()
        cy.get('#id_altura').type('1.30')
        cy.wait(3000)
        cy.get('.default').click()

        cy.wait(3000)
        cy.get('.model-user > :nth-child(2) > .addlink').click()
        cy.get('#id_username').type('70259518231')
        cy.get('#id_password1').type('ygor8500')
        cy.get('#id_password2').type('ygor8500')
        cy.get('.default').click()
        cy.wait(3000)
        cy.get('.model-useraluno > td > .addlink').click()
        cy.get('#id_user').select('70259518231');
        cy.get('#id_matricula').type('apo12345')
        cy.get('#id_nome').type('Pedro Barros barreto')
        cy.get('#id_cpf').type('70259518231')
        cy.get('#id_data_de_nascimento').type('01/05/2018')
        cy.get('#id_endereco').type('Armazém Original - Mercao da Torre - R. José Bonifácio, 747 - Torre, Recife - PE, 50710-001')
        cy.get('#id_colegio').type('Dom Domingos II')
        cy.get('#id_serie').type('1')
        cy.get('#id_turma').type('A')
        cy.get('#id_nome_responsavel').type('Antonieta Solene Lima')
        cy.get('#id_cpf_responsavel').type('73681509210')
        cy.get('#id_telefone').type('81897725630')
        cy.get('#id_email_responsavel').type('matonieta@gmail.com')
        cy.get('#id_peso').clear()
        cy.get('#id_peso').type('20.5')
        cy.get('#id_altura').clear()
        cy.get('#id_altura').type('1.28')
        cy.wait(3000)
        cy.get('.default').click()

        cy.wait(3000)
        cy.visit('/')
        cy.get('[href="/professor/"] > .botao').click()
        cy.get('#username').type('34489066420')
        cy.get('#password').type('ygor1234')
        cy.get('.btn-submit').click()

        cy.wait(3000)
        cy.get(':nth-child(1) > .nav-menu-texto').click()
        cy.get('#data').type('2004-03-04', {force: true});
        cy.get('#turma_id').select('1 - A')
        cy.get('#materia').select('Matemática')
        cy.get(':nth-child(1) > input').check()
        cy.get('button').click()
        cy.wait(3000)

        cy.visit('/admin')
        cy.get('#id_username').type('admin')
        cy.get('#id_password').type('123456')
        cy.get('.submit-row > input').click()
        cy.wait(1000)

        cy.get('.model-presenca > th > a').click()
        cy.wait(3000)

                
    });
});