# Generated by Django 5.0.3 on 2024-04-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_saude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(max_length=4)),
                ('altura', models.FloatField(max_length=4)),
                ('restricao_alimentar', models.TextField(max_length=100)),
                ('tdah', models.CharField(max_length=4)),
                ('pcd', models.CharField(max_length=4)),
            ],
        ),
    ]
