# Generated by Django 5.0.3 on 2024-04-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.PositiveIntegerField()),
                ('data_de_nascimento', models.DateTimeField(verbose_name='Created on')),
                ('endereco', models.TextField()),
                ('serie', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nome_responsavel', models.CharField(max_length=200)),
                ('cpf_responsavel', models.PositiveIntegerField()),
                ('telefone', models.PositiveIntegerField()),
                ('email_responsavel', models.EmailField(max_length=254)),
            ],
        ),
    ]
