# Generated by Django 5.0.3 on 2024-04-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_saude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(max_length=4)),
                ('altura', models.FloatField(max_length=4)),
                ('restricao_alimentar', models.TextField(max_length=100)),
                ('tdah', models.CharField(max_length=4)),
                ('pcd', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='useraluno',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
