# Generated by Django 5.0.3 on 2024-04-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0003_mensagemcontato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia_Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colegio', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('serie', models.PositiveSmallIntegerField()),
                ('matricula', models.PositiveIntegerField()),
                ('materia_1', models.CharField(max_length=200)),
                ('faltas_m1', models.PositiveSmallIntegerField()),
                ('porcentagem_m1', models.DecimalField(decimal_places=2, max_digits=2)),
                ('materia_2', models.CharField(max_length=200)),
                ('faltas_m2', models.PositiveSmallIntegerField()),
                ('porcentagem_m2', models.DecimalField(decimal_places=2, max_digits=2)),
                ('materia_3', models.CharField(max_length=200)),
                ('faltas_m3', models.PositiveSmallIntegerField()),
                ('porcentagem_m3', models.DecimalField(decimal_places=2, max_digits=2)),
                ('materia_4', models.CharField(max_length=200)),
                ('faltas_m4', models.PositiveSmallIntegerField()),
                ('porcentagem_m4', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
