# Generated by Django 5.0.3 on 2024-04-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0004_frequencia_aluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequencia_aluno',
            old_name='faltas_m1',
            new_name='faltas_da_materia_1',
        ),
        migrations.RenameField(
            model_name='frequencia_aluno',
            old_name='faltas_m2',
            new_name='faltas_da_materia_2',
        ),
        migrations.RenameField(
            model_name='frequencia_aluno',
            old_name='faltas_m3',
            new_name='faltas_da_materia_3',
        ),
        migrations.RenameField(
            model_name='frequencia_aluno',
            old_name='faltas_m4',
            new_name='faltas_da_materia_4',
        ),
        migrations.RenameField(
            model_name='frequencia_aluno',
            old_name='porcentagem_m1',
            new_name='porcentagem_da_materia_1',
        ),
        migrations.RenameField(
            model_name='frequencia_aluno',
            old_name='porcentagem_m2',
            new_name='porcentagem_da_materia_2',
        ),
        migrations.RenameField(
            model_name='frequencia_aluno',
            old_name='porcentagem_m3',
            new_name='porcentagem_da_materia_3',
        ),
        migrations.RenameField(
            model_name='frequencia_aluno',
            old_name='porcentagem_m4',
            new_name='porcentagem_da_materia_4',
        ),
    ]
