# Generated by Django 5.0.3 on 2024-04-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0005_rename_faltas_m1_frequencia_aluno_faltas_da_materia_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia_aluno',
            name='porcentagem_da_materia_1',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='frequencia_aluno',
            name='porcentagem_da_materia_2',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='frequencia_aluno',
            name='porcentagem_da_materia_3',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='frequencia_aluno',
            name='porcentagem_da_materia_4',
            field=models.CharField(max_length=3),
        ),
    ]
