# Generated by Django 5.0.3 on 2024-04-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0006_alter_frequencia_aluno_porcentagem_da_materia_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia_aluno',
            name='matricula',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='frequencia_aluno',
            name='porcentagem_da_materia_1',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='frequencia_aluno',
            name='porcentagem_da_materia_2',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='frequencia_aluno',
            name='porcentagem_da_materia_3',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='frequencia_aluno',
            name='porcentagem_da_materia_4',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='useraluno',
            name='matricula',
            field=models.CharField(max_length=4),
        ),
    ]
