# Generated by Django 5.0.4 on 2024-04-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0007_alter_frequencia_aluno_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia_aluno',
            name='porcentagem_da_materia_1',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='frequencia_aluno',
            name='porcentagem_da_materia_2',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='frequencia_aluno',
            name='porcentagem_da_materia_3',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='frequencia_aluno',
            name='porcentagem_da_materia_4',
            field=models.CharField(max_length=4),
        ),
    ]
