# Generated by Django 5.0.4 on 2024-04-06 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0008_alter_frequencia_aluno_porcentagem_da_materia_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useraluno',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensagemcontato',
            name='telefone',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='useraluno',
            name='cpf_responsavel',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='useraluno',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
