# Generated by Django 5.0.3 on 2024-04-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0011_remove_frequencia_aluno_porcentagem_da_materia_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia_aluno',
            name='user_aluno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appsmartschool.useraluno'),
        ),
    ]
