# Generated by Django 5.0.3 on 2024-04-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0012_frequencia_aluno_user_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_saude',
            name='user_aluno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appsmartschool.useraluno'),
        ),
    ]
