# Generated by Django 5.0.3 on 2024-04-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0013_dados_saude_user_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraluno',
            name='data_de_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
