# Generated by Django 5.0.3 on 2024-04-19 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0016_userfuncionario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dados_saude',
            options={'verbose_name': 'Dados de saúde', 'verbose_name_plural': 'Dados de saúde'},
        ),
        migrations.AlterModelOptions(
            name='frequencia_aluno',
            options={'verbose_name': 'Frequência', 'verbose_name_plural': 'Frequência'},
        ),
        migrations.AlterModelOptions(
            name='mensagemcontato',
            options={'verbose_name': 'Dados de contato', 'verbose_name_plural': 'Dados de contato'},
        ),
        migrations.AlterModelOptions(
            name='useraluno',
            options={'verbose_name': 'Dados aluno', 'verbose_name_plural': 'Dados aluno'},
        ),
        migrations.AlterModelOptions(
            name='userfuncionario',
            options={'verbose_name': 'Dados do funcionário', 'verbose_name_plural': 'Dados do funcionário'},
        ),
        migrations.AlterModelOptions(
            name='userprofessor',
            options={'verbose_name': 'Dados do professor', 'verbose_name_plural': 'Dados do professor'},
        ),
        migrations.CreateModel(
            name='consultar_horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colegio', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('serie', models.PositiveSmallIntegerField()),
                ('matricula', models.CharField(max_length=200)),
                ('inicio_horario_1', models.TimeField()),
                ('final_horario_1', models.TimeField()),
                ('inicio_horario_2', models.TimeField()),
                ('final_horario_2', models.TimeField()),
                ('inicio_horario_3', models.TimeField()),
                ('final_horario_3', models.TimeField()),
                ('inicio_horario_4', models.TimeField()),
                ('final_horario_4', models.TimeField()),
                ('materia_1', models.CharField(max_length=200)),
                ('materia_2', models.CharField(max_length=200)),
                ('materia_3', models.CharField(max_length=200)),
                ('materia_4', models.CharField(max_length=200)),
                ('user_aluno', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appsmartschool.useraluno')),
            ],
            options={
                'verbose_name': 'Dados de saúde',
                'verbose_name_plural': 'Dados de saúde',
            },
        ),
    ]
