# Generated by Django 5.0.4 on 2024-04-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0016_userfuncionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.PositiveSmallIntegerField()),
                ('dia_semana', models.CharField(max_length=20)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('materia', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Horário de Aula',
                'verbose_name_plural': 'Horários de Aulas',
            },
        ),
        migrations.AlterModelOptions(
            name='dados_saude',
            options={'verbose_name': 'Dados de saúde', 'verbose_name_plural': 'Dados de saúde'},
        ),
        migrations.AlterModelOptions(
            name='frequencia_aluno',
            options={'verbose_name': 'Frequência', 'verbose_name_plural': 'Frequência'},
        ),
        migrations.AlterModelOptions(
            name='mensagemcontato',
            options={'verbose_name': 'Dados de contato', 'verbose_name_plural': 'Dados de contato'},
        ),
        migrations.AlterModelOptions(
            name='useraluno',
            options={'verbose_name': 'Dados aluno', 'verbose_name_plural': 'Dados aluno'},
        ),
        migrations.AlterModelOptions(
            name='userfuncionario',
            options={'verbose_name': 'Dados do funcionário', 'verbose_name_plural': 'Dados do funcionário'},
        ),
        migrations.AlterModelOptions(
            name='userprofessor',
            options={'verbose_name': 'Dados do professor', 'verbose_name_plural': 'Dados do professor'},
        ),
    ]
