# Generated by Django 5.0.3 on 2024-04-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0017_alter_dados_saude_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultar_horario',
            options={'verbose_name': 'Horário da Turma', 'verbose_name_plural': 'Horário da Turma'},
        ),
    ]
