# Generated by Django 5.0.4 on 2024-04-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0017_horarioaula_alter_dados_saude_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horarioaula',
            old_name='dia_semana',
            new_name='dia_semana_1',
        ),
        migrations.RenameField(
            model_name='horarioaula',
            old_name='horario_fim',
            new_name='horario_fim_1',
        ),
        migrations.RenameField(
            model_name='horarioaula',
            old_name='horario_inicio',
            new_name='horario_inicio_1',
        ),
        migrations.RenameField(
            model_name='horarioaula',
            old_name='materia',
            new_name='materia_1',
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='dia_semana_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='dia_semana_3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='dia_semana_4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='dia_semana_5',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='horario_fim_2',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='horario_fim_3',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='horario_fim_4',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='horario_inicio_2',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='horario_inicio_3',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='horario_inicio_4',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='materia_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='materia_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='materia_4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
