# Generated by Django 5.0.3 on 2024-04-27 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0018_rename_dia_semana_horarioaula_dia_semana_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_1', models.CharField(default='Matéria 1', max_length=200)),
                ('materia_2', models.CharField(default='Matéria 2', max_length=200)),
                ('materia_3', models.CharField(default='Matéria 3', max_length=200)),
                ('materia_4', models.CharField(default='Matéria 4', max_length=200)),
                ('nota1_materia1', models.FloatField(max_length=4)),
                ('nota2_materia1', models.FloatField(max_length=4)),
                ('nota3_materia1', models.FloatField(max_length=4)),
                ('media_materia1', models.FloatField(max_length=4)),
                ('nota1_materia2', models.FloatField(max_length=4)),
                ('nota2_materia2', models.FloatField(max_length=4)),
                ('nota3_materia2', models.FloatField(max_length=4)),
                ('media_materia2', models.FloatField(max_length=4)),
                ('nota1_materia3', models.FloatField(max_length=4)),
                ('nota2_materia3', models.FloatField(max_length=4)),
                ('nota3_materia3', models.FloatField(max_length=4)),
                ('media_materia3', models.FloatField(max_length=4)),
                ('nota1_materia4', models.FloatField(max_length=4)),
                ('nota2_materia4', models.FloatField(max_length=4)),
                ('nota3_materia4', models.FloatField(max_length=4)),
                ('media_materia4', models.FloatField(max_length=4)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsmartschool.useraluno')),
            ],
            options={
                'verbose_name': 'Notas do aluno',
                'verbose_name_plural': 'Notas do aluno',
            },
        ),
    ]
