# Generated by Django 5.0.3 on 2024-04-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0019_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='media_materia1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='media_materia2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='media_materia3',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='media_materia4',
        ),
    ]
