# Generated by Django 5.0.4 on 2024-04-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0022_alter_disciplina_carga_horaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioaula',
            name='turma',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
