# Generated by Django 5.0.4 on 2024-04-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0023_horarioaula_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraluno',
            name='turma',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
