# Generated by Django 5.0.4 on 2024-04-29 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0024_useraluno_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioaula',
            name='turma',
            field=models.CharField(max_length=1, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]$', 'Apenas letras maiúsculas são permitidas.')]),
        ),
        migrations.AlterField(
            model_name='useraluno',
            name='turma',
            field=models.CharField(max_length=1, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]$', 'Apenas letras maiúsculas são permitidas.')]),
        ),
    ]
