# Generated by Django 5.0.4 on 2024-04-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0026_alter_dados_saude_altura_alter_dados_saude_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioaula',
            name='colegio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useraluno',
            name='colegio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
