# Generated by Django 5.0.4 on 2024-04-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0027_horarioaula_colegio_useraluno_colegio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horarioaula',
            old_name='materia_2',
            new_name='quar_materia_do_horario_1',
        ),
        migrations.RenameField(
            model_name='horarioaula',
            old_name='materia_3',
            new_name='quar_materia_do_horario_2',
        ),
        migrations.RenameField(
            model_name='horarioaula',
            old_name='materia_4',
            new_name='quar_materia_do_horario_3',
        ),
        migrations.RenameField(
            model_name='horarioaula',
            old_name='materia_1',
            new_name='seg_materia_do_horario_1',
        ),
        migrations.RemoveField(
            model_name='horarioaula',
            name='dia_semana_1',
        ),
        migrations.RemoveField(
            model_name='horarioaula',
            name='dia_semana_2',
        ),
        migrations.RemoveField(
            model_name='horarioaula',
            name='dia_semana_3',
        ),
        migrations.RemoveField(
            model_name='horarioaula',
            name='dia_semana_4',
        ),
        migrations.RemoveField(
            model_name='horarioaula',
            name='dia_semana_5',
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='quar_materia_do_horario_4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='quin_materia_do_horario_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='quin_materia_do_horario_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='quin_materia_do_horario_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='quin_materia_do_horario_4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='seg_materia_do_horario_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='seg_materia_do_horario_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='seg_materia_do_horario_4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='sex_materia_do_horario_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='sex_materia_do_horario_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='sex_materia_do_horario_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='sex_materia_do_horario_4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='ter_materia_do_horario_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='ter_materia_do_horario_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='ter_materia_do_horario_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='ter_materia_do_horario_4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
