# Generated by Django 5.0.3 on 2024-05-15 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0028_rename_materia_2_horarioaula_quar_materia_do_horario_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraluno',
            name='email',
        ),
        migrations.AddField(
            model_name='useraluno',
            name='altura',
            field=models.FloatField(default=0.0, help_text='Altura deve ser entre 0.50 m e 2 m.', max_length=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='useraluno',
            name='pcd',
            field=models.CharField(default='Não', max_length=4),
        ),
        migrations.AddField(
            model_name='useraluno',
            name='peso',
            field=models.FloatField(default=0.0, help_text='Peso deve ser entre 5 e 120KG.', max_length=4, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='useraluno',
            name='restricao_alimentar',
            field=models.TextField(default='Não possui', max_length=100),
        ),
        migrations.AddField(
            model_name='useraluno',
            name='tdah',
            field=models.CharField(default='Não', max_length=4),
        ),
    ]
