# Generated by Django 5.0.3 on 2024-05-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0029_remove_useraluno_email_useraluno_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraluno',
            name='email_responsavel',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
