# Generated by Django 5.0.4 on 2024-05-16 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0030_alter_useraluno_email_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.PositiveSmallIntegerField()),
                ('turma', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[A-Z]$', 'Apenas letras maiúsculas são permitidas.')])),
            ],
        ),
    ]
