# Generated by Django 5.0.4 on 2024-05-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0031_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='codigo_materia_1',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='codigo_materia_2',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='codigo_materia_3',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='codigo_materia_4',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='materia_1',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='materia_2',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='materia_3',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='materia_4',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
