# Generated by Django 5.0.4 on 2024-05-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0032_turma_codigo_materia_1_turma_codigo_materia_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='docente',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
