# Generated by Django 5.0.4 on 2024-05-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0033_turma_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='matricula_docente',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
