# Generated by Django 5.0.3 on 2024-05-26 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0035_alter_userprofessor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofessor',
            options={'verbose_name': 'Dados do professor', 'verbose_name_plural': 'Dados do professor'},
        ),
        migrations.AlterField(
            model_name='userprofessor',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsmartschool.useraluno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsmartschool.disciplina')),
            ],
            options={
                'verbose_name': 'Presença do aluno',
                'verbose_name_plural': 'Presenças dos alunos',
            },
        ),
        migrations.DeleteModel(
            name='Frequencia_Aluno',
        ),
    ]
