# Generated by Django 5.0.3 on 2024-05-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0036_alter_userprofessor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofessor',
            name='disciplinas',
            field=models.ManyToManyField(related_name='professores', to='appsmartschool.disciplina'),
        ),
        migrations.DeleteModel(
            name='Dados_saude',
        ),
    ]
