# Generated by Django 5.0.4 on 2024-05-30 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0037_userprofessor_disciplinas_delete_dados_saude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofessor',
            name='disciplinas',
        ),
    ]
