# Generated by Django 5.0.3 on 2024-05-31 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0038_remove_userprofessor_disciplinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsmartschool.disciplina'),
        ),
    ]
