# Generated by Django 5.0.3 on 2024-05-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0039_notas_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='materia_1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='materia_2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='materia_3',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='materia_4',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='nota1_materia1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='nota1_materia2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='nota1_materia3',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='nota1_materia4',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='nota2_materia1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='nota2_materia2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='nota2_materia3',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='nota2_materia4',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='nota3_materia1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='nota3_materia2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='nota3_materia3',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='nota3_materia4',
        ),
    ]
