# Generated by Django 5.0.3 on 2024-05-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0040_remove_notas_materia_1_remove_notas_materia_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='nota1',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='notas',
            name='nota2',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='notas',
            name='nota3',
            field=models.FloatField(default=0, max_length=4),
        ),
    ]
