# Generated by Django 5.0.3 on 2024-05-31 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsmartschool', '0041_notas_nota1_notas_nota2_notas_nota3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notas',
            options={},
        ),
        migrations.AlterField(
            model_name='notas',
            name='disciplina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appsmartschool.disciplina'),
            preserve_default=False,
        ),
    ]
